name: Deploy to GitHub Pages

# Запускаем магию только на пуши в main
on:
  push:
    branches: master
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # клонируем репозиторий на виртуальную машину
    - uses: actions/checkout@v2
    
      # ставим нужный SDK (можно использовать и более старые)
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        include-prerelease: true
        
      # генерируем статические файлы
    - name: Publish .NET Core Project
      run: dotnet publish BlazorWebAssembly/BlazorWebAssembly.csproj -c Release --output release --nologo
